services:
  awg:
    image: mejiufaro/awgrouting
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    expose:
      - ${UI_PORT}
    ports:
      - ${UI_PORT}:${UI_PORT}
      - ${WG_PORT}:${WG_PORT}/udp
    volumes:
      - ./awg-data:/etc/wireguard
    environment:
      - WG_PORT=${WG_PORT}
      - PORT=${UI_PORT}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_HOST=${IPADDR}
      - LANG=ru
      - WG_DEFAULT_ADDRESS=10.25.13.x
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_ENABLE_EXPIRES_TIME=true
      - UI_TRAFFIC_STATS=true
    container_name: awg